default:
  logging_interval: 0.5
profiles:
  profile1:
  - rpms
  - speedKmh
  - gear
  - lastTime
  - currentTime
  - session
  - kersMaxJ
  - hasERS
  - windDirection
  - brake
  profile2:
  - carCoordinates
  - flag
  - speedKmh
  - gear
  - rpms
  - aidFuelRate
  test:
  - rpms
  - speedKmh
  - gear
  - lastTime
  - currentTime
  - session
  - kersMaxJ
  - isTimedRace
  - hasExtraLap
  - finalFF
  - tyreContactHeading
  - tyreContactNormal
