default:
  logging_interval: 0.4
profiles:
  racer:
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - completedLaps
  - currentTime
  - lastTime
  - bestTime
  - fuel
  - gear
  - rpms
  - brake
  - gas
  - clutch
  - airTemp
  - roadTemp
  - speedKmh
