default:
  logging_interval: 0.1
profiles:
  alvaro_casa:
  - currentTime
  - completedLaps
  - status
  - lastTime
  - bestTime
  - distanceTraveled
  - normalizedCarPosition
  - carCoordinates
  - gas
  - brake
  - fuel
  - gear
  - rpms
  - speedKmh
  - steerAngle
  - track
  - carModel
  - sectorCount
  - trackSPlineLength
  prueba:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - mandatoryPitDone
  - windSpeed
  - gas
  - brake
  - fuel
  - gear
  - rpms
  - speedKmh
  - accG
  - airTemp
  - roadTemp
  - clutch
  racer:
  - currentTime
  - completedLaps
  - status
  - lastTime
  - bestTime
  - distanceTraveled
  - normalizedCarPosition
  - carCoordinates
  - gas
  - brake
  - fuel
  - gear
  - rpms
  - speedKmh
  - accG
  - steerAngle
  - track
  - carModel
  - sectorCount
  test1:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - brake
  - airTemp
  - roadTemp
  - clutch
  - accG
  test2:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - brake
  - airTemp
  - roadTemp
  - clutch
  - accG
  - fuel
