default:
  logging_interval: 0.4
profiles:
  profile1: &id001
  - speedKmh
  - rpms
  - gear
  - fuel
  - brake
  - gas
  - windDirection
  - tyreWear
  - suspensionTravel
  - status
  - distanceTraveled
  profile2:
  - carCoordinates
  - flag
  - speedKmh
  - gear
  - rpms
  - aidFuelRate
  test:
  - rpms
  - speedKmh
  - gear
  - lastTime
  - currentTime
  - session
  - kersMaxJ
  - isTimedRace
  - hasExtraLap
  - finalFF
  - tyreContactHeading
  - tyreContactNormal
  test_1_lambo: *id001
