default:
  logging_interval: 0.2
profiles:
  racer:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - gas
  - brake
  - gear
  - rpms
  - speedKmh
  - airTemp
  - roadTemp
  - clutch
  - accG
  - fuel
  test1:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - brake
  - airTemp
  - roadTemp
  - clutch
  - accG
  test2:
  - currentTime
  - lastTime
  - bestTime
  - completedLaps
  - position
  - iCurrentTime
  - iLastTime
  - iBestTime
  - brake
  - airTemp
  - roadTemp
  - clutch
  - accG
  - fuel
