profiles:
  tire_management:
    - tyreWear
    - tyreTempI
    - tyreTempM
    - tyreTempO
    - wheelLoad
    - surfaceGrip
  racing:
    - speedKmh
    - rpms
    - gear
    - gas
    - brake
    - drs
    - tc
    - abs
  custom:
    - rpms
    - gear
    - gas
    

